export const COLL_USERS = 'users'
export const USERS_NGO = 'ngo'
export const USERS_CORPRATE = 'corprate'
export const COLL_USER_CORPRATE = 'corprate'
export const COLL_NGO_ACTIVITIES = 'ngo-activities'
export const COLL_CORPRATE_ACTIVITIES = 'corprate-activities'
export const COLL_NGO_DONATIONS = 'ngo-donations'
export const COLL_CORPRATE_DONATIONS = 'corprate-donations'
